# Matrix Factorization using Gradient Descent

In this excercise, you are required to implement matrix factorization method, specifically [Non-Negative Matrix Factorization (NMF)](https://en.wikipedia.org/wiki/Non-negative_matrix_factorization), using gradient descent. You have to apply the matrix factorization to solve topic modeling. 

(Please refer to the tutorial on basics of topic modeling, LSI with SVD (Tutorial Set 4), for details on LSI)

## Applying NMF to solve Topic Modeling
Given a term document matrix $V$, NMF factorizes it into two matrix $W$ and $H$ with the property that all three documents have no negative elements.
<img src="content/NMF.png" alt="Non-negative matrix factorization" style="width: 80%">

In Non-negative Matrix Factorization, a document-term matrix is approximately factorized into term-feature and feature-document matrices.

$V = WH$ Matrix multiplication can be implemented as computing the column vectors of $V$ as linear combinations of the basis vectors (column vectors) in $W$ (or the topics discovered from the documents) using coefficients supplied by columns of $H$ (or the membership weights for the topics in each document). That is, each column of V can be computed as follows:
$$ v_i = W h_i$$

In what follows, we will first see an example of applying NMF by using [SKLearn NMF API](https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.NMF.html) for the task of topic modeling. Later you will be required to implement NMF using gradient descent.

### Scikit-Learn implementation of NMF for topic modeling
Given a set of multivariate  $n$-dimensional data vectors, they are put into an  $n\times m$  matrix  $V$  as its columns, where  $m$  is the number of examples in the data set. This matrix  $V$  is approximately factorized into an  $n \times t$  matrix  $W$  and an  $t \times m$  matrix  $H$ , where  $t$  is generally less than  $n$  or  $m$ . Hence, this results in a compression of the original data matrix.

In terms of topic modeling, the input document-term matrix  $V$  is factorized into a  $n \times t$  document-topic matrix and a  $t \times m$  topic-term matrix, where  $t$  is the number of topics produced. Similar to tutorial 4, we will be using 20 NewsFetch dataset for the task.

#### Imports

In [1]:
import numpy as np
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import TfidfVectorizer
import matplotlib.pyplot as plt

%matplotlib inline

#### Setup data

In [2]:
categories = ['alt.atheism', 'talk.religion.misc', 'comp.graphics', 'sci.space']
remove = ('headers', 'footers', 'quotes')
newsgroups_train = fetch_20newsgroups(subset='train', categories=categories, remove=remove)
newsgroups_test = fetch_20newsgroups(subset='test', categories=categories, remove=remove)


#### Compute document features

In [3]:
vectorizer_tfidf = TfidfVectorizer(stop_words='english')
vectors_tfidf = vectorizer_tfidf.fit_transform(newsgroups_train.data).todense() # (documents, vocab)
vectors_tfidf.shape

(2034, 26576)

#### Compute NMF using Scikit Learn library

We will also write a function to display top 8 words for each topic.

In [4]:
num_top_words=8
vocab = np.array(vectorizer_tfidf.get_feature_names())

def show_topics(a):
    top_words = lambda t: [vocab[i] for i in np.argsort(t)[:-num_top_words-1:-1]]
    topic_words = ([top_words(t) for t in a])
    return [' '.join(t) for t in topic_words]

In [5]:
from sklearn import decomposition

d = 5 # num topics
clf = decomposition.NMF(n_components=d, random_state=1)

In [22]:
print(vectors_tfidf.shape)
W1 = clf.fit_transform(vectors_tfidf)
H1 = clf.components_

print(W1, H1)

(2034, 26576)
[[0.00184629 0.09795391 0.         0.00617658 0.00987797]
 [0.02899257 0.         0.00095132 0.         0.00682032]
 [0.01811117 0.00557737 0.00789343 0.02896533 0.        ]
 ...
 [0.00501303 0.09446731 0.00337837 0.02123326 0.        ]
 [0.05976245 0.00276049 0.         0.00224685 0.07556606]
 [0.         0.         0.         0.         0.        ]] [[0.00000000e+00 2.34542325e-02 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [2.51762649e-02 5.83391882e-03 1.21225999e-03 ... 7.13297924e-07
  1.42659585e-06 2.62821549e-03]
 [3.35184204e-02 5.97801416e-02 3.38075316e-03 ... 6.20648349e-05
  1.24129670e-04 3.91526881e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 0.00000000e+00
  0.00000000e+00 1.71103370e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 8.02911114e-06
  1.60582223e-05 0.00000000e+00]]


In [7]:
show_topics(H1)

['people don think just like objective say morality',
 'graphics thanks files image file program windows know',
 'space nasa launch shuttle orbit moon lunar earth',
 'ico bobbe tek beauchaine bronx manhattan sank queens',
 'god jesus bible believe christian atheism does belief']

# Excercise

## NMF using SGD

In stochastic gradient descent (SGD), we evaluate our loss function on just a sample of our data (sometimes called a mini-batch). We would get different loss values on different samples of the data, so this is why it is stochastic. It turns out that this is still an effective way to optimize, and it's much more efficient!

### Applying SGD to NMF

Goal: Decompose $V\;(m \times n)$ into
$$ V \approx WH$$
where $W\;(m \times d)$ and $H\;(d \times n)$, $H,\;W\; \geq \;0$, and we've minimized the Frobenius norm of $V-WH$. The objective function can therefore be written as the following:
$$
\min_{H \geq 0, W \geq 0} F(H,W) = \frac{1}{2} ||V - WH||^{2} + \frac{\lambda}{2} \left( ||H||^2 + ||W||^2 \right)
$$

### Implementation of NMF using SGD (Excercise)
__Approach:__ Given the objective function above, pick random positive $W$ & $H$, and then use SGD to optimize. 

(Note that the objective function is non-convex in nature, and is convex only if we consider $H$ and $W$ separately. You can directly write the gradient descent rule for the objective function presented above)



In [26]:
''' WRITE YOUR CODE BELOW '''

lmbda = 0.001
mu = 1e-6

# We set an initialization based on the expected final values 
# (from the previous cell)
def init_weights(a, b):
    return np.abs(np.random.normal(0, 0.01, size=(a, b)))

def ret_jacobian(V, W, H):
    J_W = (W @ H - V) @ H.T + lmbda * W
    J_H = W.T @(W @ H - V) + lmbda * H
    return J_W, J_H

m, n = vectors_tfidf.shape
W = init_weights(m, d)
H = init_weights(d, n)

N_ITER = 10
alpha = 0.002

for i in range(N_ITER):
    
    J_W, J_H = ret_jacobian(vectors_tfidf, W, H)
    W -= alpha * J_W
    H -= alpha * J_H
    
    loss = np.linalg.norm(vectors_tfidf - W @ H)
    
    print("Iter {}, loss = {}".format(i, loss))

Iter 0, loss = 44.423958039235586
Iter 1, loss = 44.42239537030184
Iter 2, loss = 44.42088481255146
Iter 3, loss = 44.41942375984226
Iter 4, loss = 44.41800974672623
Iter 5, loss = 44.41664043965804
Iter 6, loss = 44.41531362883882
Iter 7, loss = 44.41402722064185
Iter 8, loss = 44.41277923057385
Iter 9, loss = 44.41156777672879


In [27]:
show_topics(H)

['impacting increments needed eventuality cis disgust 7400 rainbow',
 '_body arthritis computing female bullwhip weakest retorts abortion',
 'afanh 250k coherent relative consulted sahara 695 oto',
 'city missile proceedings slmr amaze badges cyberpunk wickard',
 'inclusive appendix bps madamme brazenly ucsd throwing droemer']